version: "3"
services:
  apollo_server:
      container_name: apollo_asteroids
      restart: always
      image: apollo_server
      build:
          context: ./apollo_server
      volumes:
          - ./apollo_server/:/usr/src/app
      environment:
          - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
          - NEW_RELIC_HOST=${NEW_RELIC_HOST}
          - NEW_RELIC_INFINITE_TRACING_TRACE_OBSERVER_HOST=${NEW_RELIC_INFINITE_TRACING_TRACE_OBSERVER_HOST}
          - NASA_API_KEY=${NASA_API_KEY}
      networks:
          - network
      ports:
          - 4000:4000

networks:
    network:

volumes:
    db: